---
- name: Provisioning server
  hosts: all
  become: yes
  tasks:
    - name: Install NTP pkg in CentOS
      yum:
        name: "{{item}}"
        state: present
      when: ansible_distribution == "CentOS"
      loop:
        - chrony
        - wget
        - git
        - zip
        - unzip

    - name: Install NTP pkg in Ubuntu
      apt:
        name: "{{item}}"
        state: present
      when: ansible_distribution == "Ubuntu"
      loop:
        - chrony
        - wget
        - git
        - zip
        - unzip

    - name: Start and enable NTP service
      service:
        name: chronyd
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"

    - name: Start and enable NTP service on Ubuntu
      service:
        name: chrony
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"


    - name: Add Group
      group: 
       name: devops
       state: present

    - name: Add users
      user: 
        name: "{{item}}"
        state: present
        groups: devops
      loop: "{{usernames}}"
    
    - name: Add motd banner
      copy:
        content: "This {{ansible_distribution}} is managed by Ansible \n"
        dest: /etc/motd

    - name: Add ssh banner
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "#Banner none"
        line: "Banner /etc/motd"
        state: present

    - name: Restart sshd service
      service: 
        name: sshd
        state: restarted

    - name: Update NTP conf in debian
      template: 
        src: templates/ntp_debian.conf.j2
        dest: /etc/chrony/chrony.conf
      when: ansible_os_family == "Debian"

    - name: Update NTP conf in Redhat
      template:
        src: templates/ntp_redhat.conf.j2
        dest: /etc/chrony.conf
      when: ansible_os_family == "RedHat"

    - name: Restart chronyd service
      service: 
        name: chronyd
        state: restarted

    





