---
- name: Provisioning server
  hosts: all
  become: yes
  tasks:
    - name: Install NTP pkg in CentOS
      yum:
        name: "{{item}}"
        state: present
      when: ansible_distribution == "CentOS"
      loop:
        - chrony
        - wget
        - git
        - zip
        - unzip

    - name: Install NTP pkg in Ubuntu
      apt:
        name: "{{item}}"
        state: present
      when: ansible_distribution == "Ubuntu"
      loop:
        - chrony
        - wget
        - git
        - zip
        - unzip

    - name: Start and enable NTP service
      service:
        name: chronyd
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"

    - name: Start and enable NTP service on Ubuntu
      service:
        name: chrony
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"


    - name: Add Group
      group: 
       name: devops
       state: present

    - name: Add users
      user: 
        name: "{{item}}"
        state: present
        groups: devops
      loop: "{{usernames}}"
     





